### PR TITLE
Upgrade projects to .net core 3.1

### PR DESCRIPTION
**Pull request by RickFrankel**
Upgrade to .Net Core 3.1 and format all files based on VS 2019 Cleanup Profiles.

### CODE REVIEW

**Comment by otavioalfenas** [comment]
Hi @RickFrankel can you include AddCookies e WithCookies into Fluent Class?

**Comment by RickFrankel** [comment]
> Hi @RickFrankel can you include AddCookies e WithCookies into Fluent Class?

Sorry about that.  Updated and merged all the latest code in.
Thanks
Rick

**Comment by otavioalfenas** [comment]
Hi @RickFrankel Could you run the push command on your branch so that your history remains in git, please, so that your branch will appear in the project's branches?

If you have any questions, you can contact me at the email in the readme.
And thanks again for converting the code to .netcore

**Comment by RickFrankel** [comment]
Everything looks pushed from my side.

**Comment by otavioalfenas** [comment]
> Everything looks pushed from my side.

Can you try run this command please: git push --set-upstream origin NetCore31Upgrade

Because Your branch does not appear here for me to merge. But anyway,
I just need the branch to leave the file tree as below:
- Readme
- Readme -EN
- License
-Src
  -NetFramework4.6.1
     --- Code, project and test folder here
  -NetCore3.1.
     --- Code, project and test folder here

If you have no problem for me, I can download and mount it here, but I believe it is not the right one, because you will lose your history, because your branch is only in your workspace
branches

**Comment by RickFrankel** [comment]
Ok.  Have a look now and see if it's what you were after.

This is what I see

image

**Comment by otavioalfenas** [comment]
Very nice everthing ok.
I will merge them both, thanks again

**Comment by otavioalfenas** [comment]
Resolved, and published

**Pull request closed without merging**
